server:
  port: 8071
#是否开启 swagger-ui
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
# 推送
push:
  # 当前推送方式
  active: jpush
  jpush:
    appKey: dccda52cf9b3e574ee5beb13
    masterSecret: 1e69202b4db58124b00ad42c
